version: "2"

linters:
  default: all
  disable:
    - depguard
    - forcetypeassert
    - gochecknoglobals
    - godox
    - ireturn
    - mnd
    - nakedret
    - paralleltest
    - testpackage
    - varnamelen
    - exhaustruct
    - revive
    - err113
    - wsl
    - nonamedreturns
    - nolintlint
    - forbidigo

  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: -1
      statements: 60
    lll:
      line-length: 130

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mvisonneau)
