linters:
  enable-all: true
  disable:
    # Deprecated ones
    - golint
    - interfacer
    - maligned
    - scopelint
    - ifshort
    - nosnakecase

    # We don't want these ones
    - depguard
    - exhaustivestruct
    - forcetypeassert
    - gochecknoglobals
    - godox
    - goerr113
    - ireturn
    - nakedret
    - testpackage
    - varnamelen

    # To assess later on
    - paralleltest

linters-settings:
  funlen:
    lines: -1 # (disabled)
    statements: 60

  cyclop:
    max-complexity: 20

  lll:
    line-length: 130

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mvisonneau)
