before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/s5
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: &author Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: &description Safely Store Super Sensitive Stuff
    license: &license Apache-2.0
    homepage: &homepage https://github.com/mvisonneau/s5
    vendor: *author
    file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - deb
      - rpm

brews:
  - description: *description
    homepage: *homepage
    folder: Formula
    tap:
      owner: mvisonneau
      name: homebrew-tap

scoop:
  description: *description
  homepage: *homepage
  license: *license
  bucket:
    owner: mvisonneau
    name: scoops

snapcrafts:
  - name: mvisonneau-s5
    summary: *description
    description: Cipher/Decipher arbitrary text in any file type
    license: *license
    grade: stable
    apps:
      s5:
        plugs: [home, network]

dockers:
  - image_templates:
      - 'docker.io/mvisonneau/s5:{{ .Tag }}-amd64'
      - 'ghcr.io/mvisonneau/s5:{{ .Tag }}-amd64'
    ids: [s5]
    goarch: amd64
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/s5:{{ .Tag }}-arm64v8'
      - 'ghcr.io/mvisonneau/s5:{{ .Tag }}-arm64v8'
    ids: [s5]
    goarch: arm64
    use_buildx: true
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/mvisonneau/s5:{{ .Tag }}
    image_templates:
      - docker.io/mvisonneau/s5:{{ .Tag }}-amd64
      - docker.io/mvisonneau/s5:{{ .Tag }}-arm64v8

  - name_template: ghcr.io/mvisonneau/s5:{{ .Tag }}
    image_templates:
      - ghcr.io/mvisonneau/s5:{{ .Tag }}-amd64
      - ghcr.io/mvisonneau/s5:{{ .Tag }}-arm64v8

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_sha512sums.txt'
  algorithm: sha512

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

changelog:
  skip: true
