version: 2
before:
  hooks:
    - make man-pages
    - make autocomplete-scripts

builds:
  - main: ./cmd/s5
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
    flags:
      - -trimpath
    ignore:
      - { goos: darwin, goarch: 386 }
      - { goos: darwin, goarch: arm }
      - { goos: windows, goarch: arm }
      - { goos: windows, goarch: arm64 }

universal_binaries:
  - {}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - helpers/*

nfpms:
  - maintainer: &author Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: &description Safely Store Super Sensitive Stuff
    license: &license Apache-2.0
    homepage: &homepage https://github.com/mvisonneau/s5
    vendor: *author
    file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    bindir: /usr/local/sbin
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: ./helpers/autocomplete/bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/autocomplete/zsh
        dst: /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/copyright
        file_info:
          mode: 0644

brews:
  - description: *description
    homepage: *homepage
    license: *license
    directory: Formula
    repository:
      owner: mvisonneau
      name: homebrew-tap
    test: |
      system "#{bin}/{{ .ProjectName }} -v"
    install: |-
      bin.install "{{ .ProjectName }}"
      bash_completion.install "./helpers/autocomplete/bash" => "{{ .ProjectName }}"
      zsh_completion.install "./helpers/autocomplete/zsh" => "_{{ .ProjectName }}"
      man1.install "./helpers/manpages/{{ .ProjectName }}.1.gz"

scoops:
  - description: *description
    homepage: *homepage
    license: *license
    repository:
      owner: mvisonneau
      name: scoops

snapcrafts:
  - summary: *description
    description: Monitor GitLab CI pipelines related metrics.
    license: *license
    grade: stable
    apps:
      s5:
        plugs: [home, network]

dockers:
  - image_templates:
      - "docker.io/mvisonneau/s5:{{ .Tag }}-amd64"
      - "ghcr.io/mvisonneau/s5:{{ .Tag }}-amd64"
      - "quay.io/mvisonneau/s5:{{ .Tag }}-amd64"
    ids: [s5]
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - "docker.io/mvisonneau/s5:{{ .Tag }}-arm64"
      - "ghcr.io/mvisonneau/s5:{{ .Tag }}-arm64"
      - "quay.io/mvisonneau/s5:{{ .Tag }}-arm64"
    ids: [s5]
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - "docker.io/mvisonneau/s5:{{ .Tag }}-armv6"
      - "ghcr.io/mvisonneau/s5:{{ .Tag }}-armv6"
      - "quay.io/mvisonneau/s5:{{ .Tag }}-armv6"
    ids: [s5]
    goarch: arm
    goarm: 6
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - "docker.io/mvisonneau/s5:{{ .Tag }}-armv7"
      - "ghcr.io/mvisonneau/s5:{{ .Tag }}-armv7"
      - "quay.io/mvisonneau/s5:{{ .Tag }}-armv7"
    ids: [s5]
    goarch: arm
    goarm: 7
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/s5
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/mvisonneau/s5:{{ .Tag }}
    image_templates:
      - docker.io/mvisonneau/s5:{{ .Tag }}-amd64
      - docker.io/mvisonneau/s5:{{ .Tag }}-arm64
      - docker.io/mvisonneau/s5:{{ .Tag }}-armv6
      - docker.io/mvisonneau/s5:{{ .Tag }}-armv7

  - name_template: ghcr.io/mvisonneau/s5:{{ .Tag }}
    image_templates:
      - ghcr.io/mvisonneau/s5:{{ .Tag }}-amd64
      - ghcr.io/mvisonneau/s5:{{ .Tag }}-arm64
      - ghcr.io/mvisonneau/s5:{{ .Tag }}-armv6
      - ghcr.io/mvisonneau/s5:{{ .Tag }}-armv7

  - name_template: quay.io/mvisonneau/s5:{{ .Tag }}
    image_templates:
      - quay.io/mvisonneau/s5:{{ .Tag }}-amd64
      - quay.io/mvisonneau/s5:{{ .Tag }}-arm64
      - quay.io/mvisonneau/s5:{{ .Tag }}-armv6
      - quay.io/mvisonneau/s5:{{ .Tag }}-armv7

checksum:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_sha512sums.txt"
  algorithm: sha512

signs:
  - artifacts: checksum
    args:
      [
        "-u",
        "C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

changelog:
  disable: true
