version: 2
before:
  hooks:
    - make autocomplete-scripts

builds:
  - main: ./cmd/s5
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mvisonneau/s5/internal/app.Version={{.Version}}
    ignore:
      - { goos: darwin, goarch: 386 }
      - { goos: darwin, goarch: arm }
      - { goos: windows, goarch: arm }

universal_binaries:
  - {}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE
      - helpers/*

nfpms:
  - maintainer: &author Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: &description Safely Store Super Sensitive Stuff
    license: &license Apache-2.0
    homepage: &homepage https://github.com/mvisonneau/s5
    vendor: *author
    file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    bindir: /usr/local/sbin
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: ./helpers/autocomplete/bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./helpers/autocomplete/zsh
        dst: /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/copyright
        file_info:
          mode: 0644

homebrew_casks:
  - description: *description
    homepage: *homepage
    license: *license
    directory: Formula
    repository:
      owner: mvisonneau
      name: homebrew-tap
    completions:
      bash: helpers/autocomplete/bash
      zsh: helpers/autocomplete/zsh
      fish: helpers/autocomplete/fish

scoops:
  - description: *description
    homepage: *homepage
    license: *license
    repository:
      owner: mvisonneau
      name: scoops

snapcrafts:
  - summary: *description
    description: Monitor GitLab CI pipelines related metrics.
    license: *license
    grade: stable
    apps:
      s5:
        plugs: [home, network]

dockers_v2:
  - images:
      - docker.io/mvisonneau/s5
      - ghcr.io/mvisonneau/s5
      - quay.io/mvisonneau/s5
    tags:
      - "{{ .Tag }}"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "{{ .ProjectName }}"
      org.opencontainers.image.url: "https://github.com/mvisonneau/s5"
      org.opencontainers.image.source: "https://github.com/mvisonneau/s5"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: "Apache-2.0"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_sha512sums.txt'
  algorithm: sha512

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

changelog:
  disable: true
